// This file was generated by Dashcode from Apple Computer, Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateText('latest_text', { text: 'Seneste radio:' });
    CreateText('live_text', { text: 'Live radio:' });
    CreateText('latest_text3', { text: 'Tv program:' });
    CreateText('live_text4', { text: 'Udgave:' });
    CreateText('live_text9', { text: 'Live tv:' });
    CreateText('text', { text: 'Valg:' });
    CreateGlassButton('glassbutton', { text: 'Play', onclick: 'play' });
    CreateGlassButton('glassbutton1', { text: 'Pause', onclick: 'pause' });
    CreateGlassButton('glassbutton2', { text: 'Stop', onclick: 'stop' });
    CreateGlassButton('glassbutton3', { text: 'fullscreen', onclick: 'fullscreen' });
    CreateGlassButton('glassbutton4', { text: 'Test', onclick: 'testReq' });
}
window.addEventListener('load', setupParts, false);
